### ISSUE TITLE
New feature (Lubed and stock)

### ISSUE THREAD

**Issue by TheMonkCoder** [tplai/kbsim#22]
# **New Feature**

<h3>You should add a new feature that allows you to choose between lubed and stock switches. 
Not under the switches collum but a new collum. I think that with it that you should add a film one with the stock, and lubed. And combinations like lubed and filmed. </h3>

(P.S loving the site don't stop and keep going.)

**Comment by tplai** [comment]
This is a great idea that I think would be a good addition to the site. But I'm going to be the bringer of bad news and say I don't think I'd be able to implement this to the point where I'd be happy releasing it.

The key switches I sourced for the current library were from high-quality sound tests (Koen Romers and Taeha types) that come from a variety of different keyboards (most all of them are lubed). As you might know, different things influence the sound of a keyboard like case size/shape, plate material, layout, audio setup, and even table setup (surprisingly even your table or mousepad influences the sound of your keyboard). Point being, there are already a lot of variables to account for. So if I were to find an unlubed typing test for Cherry MX Blacks to match the current lubed typing test, it wouldn't truly be a 1:1 comparison since the other variables from the OG typing test might be different.

If it helps at all, pretty much all of the switches on the site are already lubed.

**Comment by tplai** [comment]
I recommend checking this video by nearLucid where he covers ohw just a few variables like his desk and recording device can change a sound test drastically

https://www.youtube.com/watch?v=TjA7Oap5XKo

**Comment by imjustakeyboredperson** [comment]
Yo tplai keep this up is s#it is amazing

**Comment by tplai** [comment]
Closing this issue for now.
